version: '3'

services:
  nacos:
    container_name: nacos
    image: nacos/nacos-server
    restart: always
    environment:
      PREFER_HOST_MODE: hostname
      MODE: standalone
      JVM_XMS: 256m
      JVM_XMX: 256m
      JVM_XMN: 128m
      JVM_MS: 32m
      JVM_MMS: 48m
    volumes:
      - ~/docker-volumes/nacos/logs:/home/nacos/logs
      - ~/docker-volumes/nacos/init.d:/home/nacos/init.d
    networks:
      - compose
    ports:
      - '8848:8848'

networks:
  compose:
    external: true
