version: '3'

services:
  socks2http:
    container_name: socks2http
    image: chenyingzhou/socks2http
    restart: always
    ports:
      - 1081:1081
    environment:
      SOCKS_HOST: 192.168.4.23:1080
