version: '3'

services:
  mysql:
    image: mysql:8.0
    volumes:
      # mysql数据目录
      - ~/docker-volume/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - lnmp
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
  redis:
    image: chenyingzhou/redis:latest
    volumes:
      # redis持久化目录
      - ~/docker-volume/redis:/var/lib/redis
    ports:
      - 6379:6379
    networks:
      - lnmp
    restart: always
  php-ng:
    image: chenyingzhou/php72-ng:latest
    volumes:
      # ng配置和code目录
      - ~/docker-volume/php72-ng/ng-conf.d:/etc/nginx/conf.d
      - ~/source:/var/www/http
    ports:
      - 80:80
      - 443:443
    networks:
      - lnmp
    depends_on:
      - mysql
      - redis
    restart: always

networks:
  lnmp:
