version: '3'

services:
  nexus3:
    container_name: nexus3
    image: sonatype/nexus3
    restart: always
    volumes:
      - ~/docker-volumes/nexus:/nexus-data
    ports:
      - 8081:8081
    environment:
      INSTALL4J_ADD_VM_PARAMS: -Xms320m -Xmx320m
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.6
    restart: always
    volumes:
      - ~/docker-volumes/zookeeper/data:/data
      - ~/docker-volumes/zookeeper/datalog:/datalog
      - ~/docker-volumes/zookeeper/logs:/logs
    ports:
      - 2181:2181
    environment:
      JVMFLAGS: -Xms64m -Xmx128m
  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.12-2.5.0
    restart: always
    volumes:
      - ~/docker-volumes/kafka:/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_HEAP_OPTS: -Xms128m -Xmx512m
    depends_on:
      - zookeeper
  maxwell:
    container_name: maxwell
    image: zendesk/maxwell
    restart: always
    environment:
      MAXWELL_PRODUCER: kafka
      KAFKA_BROKERS: kafka:9092
      MYSQL_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MAXWELL_OPTIONS: --port=3306 --kafka_topic=maxwell_%{database}_%{table} --filter=exclude:*.*,include:maxwell_source.*
      JAVA_OPTS: -Xms128m -Xmx128m
    depends_on:
      - kafka
  nacos:
    container_name: nacos
    image: nacos/nacos-server
    restart: always
    environment:
      PREFER_HOST_MODE: hostname
      MODE: standalone
      JVM_XMS: 256m
      JVM_XMX: 256m
      JVM_XMN: 128m
      JVM_MS: 32m
      JVM_MMS: 48m
    volumes:
      - ~/docker-volumes/nacos/logs:/home/nacos/logs
      - ~/docker-volumes/nacos/init.d:/home/nacos/init.d
    ports:
      - 8848:8848
  es:
    container_name: es
    image: elasticsearch:7.10.1
    restart: always
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    volumes:
      - ~/docker-volumes/es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    container_name: kibana
    image: kibana:7.10.1
    restart: always
    environment:
      ELASTICSEARCH_URL: http://es:9200
      ELASTICSEARCH_HOSTS: '["http://es:9200"]'
    ports:
      - 5601:5601
    depends_on:
      - es