version: '2'
services:
  namesrv:
    image: apache/rocketmq:4.9.2
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    environment:
      JAVA_OPT: -Xmx128m
    volumes:
      - ~/docker-volumes/rocketmq/namesrv/logs:/home/rocketmq/logs
    command: sh mqnamesrv
  broker:
    image: apache/rocketmq:4.9.2
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
      JAVA_OPT_EXT: -Xms128M -Xmx128M -Xmn64M
    volumes:
      - ~/docker-volumes/rocketmq/broker/conf/broker.conf:/home/rocketmq/rocketmq-4.9.2/conf/broker.conf
      - ~/docker-volumes/rocketmq/broker/logs:/home/rocketmq/logs
      - ~/docker-volumes/rocketmq/broker/store:/home/rocketmq/store
    command: sh mqbroker -n namesrv:9876 -c ../conf/broker.conf
    depends_on:
      - namesrv
  mqconsole:
    image: styletang/rocketmq-console-ng
    container_name: rmqconsole
    ports:
      - 19876:8080
    environment:
      JAVA_OPTS: -Drocketmq.namesrv.addr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=falses -Xmx128m
    depends_on:
      - namesrv

