version: '3.7'
services:
  rocketmq:
    image: chenyingzhou/rocketmq:4.9.2
    container_name: rocketmq
    restart: always
    networks:
      - compose
    ports:
      - "9876:9876"
      - "10909-10912:10909-10912"
    environment:
      NAMESRV_MEM_OPTS: -Xms16M -Xmx16M -Xmn8M -XX:MaxDirectMemorySize=16M
      BROKER_MEM_OPTS: -Xms32M -Xmx32M -Xmn16M -XX:MaxDirectMemorySize=32M
      BROKER_IP: host.docker.internal # MAC/WINDOWS不需要修改，或者直接删除该变量，LINUX需要修改为宿主机IP
    volumes:
      - ~/docker-volumes/rocketmq/logs:/home/rocketmq/logs
      - ~/docker-volumes/rocketmq/store:/home/rocketmq/store
  rmqconsole:
    image: styletang/rocketmq-console-ng
    container_name: rmqconsole
    restart: always
    networks:
      - compose
    ports:
      - "19876:8080"
    environment:
      JAVA_OPTS: -Drocketmq.namesrv.addr=rocketmq:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false -Xmx64m
    depends_on:
      - rocketmq

networks:
  compose:
    external: true