version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    volumes:
      - ~/docker-volumes/mysql/data:/var/lib/mysql
      - ~/docker-volumes/mysql/conf:/etc/mysql/conf.d/mysqld.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    command: --default-authentication-plugin=mysql_native_password
  redis:
    container_name: redis
    image: redis:6
    restart: always
    volumes:
      - ~/docker-volumes/redis:/data
    ports:
      - "6379:6379"
